version: "3.8"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - todo-network
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: secret

  web:
    image: maximepolese/todo-app:1.0.0
    ports:
      - 3000:3000
    networks:
      - todo-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    depends_on:
      - mysql

volumes:
  todo-mysql-data:

networks:
  todo-network: